# numpy get started

- numpy 提供了一种数组类型， 高维数组，提供了一个数据分析的运算基础，
- 一般是二维表

In [2]:
import numpy as np

In [2]:
np.__version__

'1.25.2'

# 1、numpy的数组概念
- c语言中数组是数据类型一致的连续的一个内存空间，
- python 的列表，在c语言的描述为一个指针数组， 列表里的数据类型可以不一致，但是他们的位置指针都是相同的，
- numpy的数组，就是一个【有序】【相同数据类型】的集合
- numpy如果传入的类型同步，numpy会强制统一：str>flo>int

   

In [3]:
array=np.array([1,3,14,'hello'])

In [4]:
array

array(['1', '3', '14', 'hello'], dtype='<U11')

In [5]:
names=["tom","hellon","jacky"]
array1= np.array(names)
array1

array(['tom', 'hellon', 'jacky'], dtype='<U6')

In [6]:
age =[15,18,22]
array2 = np .array(age,dtype=np.float32)
age

[15, 18, 22]

## 1) np.ones(shape=(5,3))
shape =(m,n) m行n列  
shape=(m)  m个元素的一维数组  
shape = (m,)m个元素的一维数组  
shape =(m,1) ,m行 1列 二维数组  
shape =(1,n)， 1行n列 二维数组  

In [7]:
#构造5行3列的二维数组
np.ones(shape=(5,3),dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [8]:
#构造长度为3的一维数组
np.ones(shape=(3))

array([1., 1., 1.])

In [9]:
#构造一个3行1列的二维数组
np.ones(shape=(3,1))

array([[1.],
       [1.],
       [1.]])

In [10]:
#构造一个1行3列的二维数组
np.ones(shape=(1,3))

array([[1., 1., 1.]])

## 2） np.zeros(shape,dtype=float,order='C')

In [11]:
np.zeros(shape=(5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
# 构造一个三维数组,
np.zeros(shape=(2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## 3) np.full(shape,fill_value,dtype=None,order='C')

In [13]:
np.full(shape=(2,3),fill_value=6)

array([[6, 6, 6],
       [6, 6, 6]])

## 4) np.eye(N,M=None,K=0,dtype=float)

In [14]:
#单位矩阵，L2正则项
#生成一个三阶单位矩阵
np.eye(N=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.eye(N=3,M=4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [16]:
np.eye(N=5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

## 5)np.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None)

In [17]:
#等差数列
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [18]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
np.linspace(0,10,10,endpoint=False)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## 6) np.arange(start,stop,step, dtype-None)

In [20]:
np.arange(0,10,step=1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 7）np.random.ranint(low,high=None,size=None,dtype='l')

In [21]:
# size 同 shape
np.random.randint(10,100,size=(5,5))

array([[24, 23, 24, 85, 33],
       [70, 80, 15, 40, 70],
       [81, 35, 44, 94, 28],
       [10, 13, 30, 78, 12],
       [95, 61, 90, 27, 38]])

## 8) 正态分布函数
- np.random.randn(d0,d1,……dn) 标准正太分布 [-1,0,1]
- np.random.normal()普通正态分布
  

In [22]:
np.random.rand(3,5)

array([[0.01021104, 0.58039702, 0.82856627, 0.80479887, 0.46503711],
       [0.02031849, 0.39185965, 0.88782964, 0.36292203, 0.3890956 ],
       [0.70612938, 0.45440232, 0.29456448, 0.22308439, 0.15119055]])

In [23]:
np.random.normal(loc=170,scale=10,size=(5,3))

array([[186.01660832, 169.41505416, 161.18853552],
       [166.10032563, 158.63430226, 159.01237495],
       [168.32062759, 162.80447098, 187.00449687],
       [183.27782004, 170.08325622, 159.71792621],
       [162.19383933, 176.5040766 , 170.93824097]])

## 9) np.random.random(size=None)
- 生成0到1的随机数，左闭右开
  

In [24]:
np.random.random(size=(3,5))

array([[0.20970342, 0.32998199, 0.43755377, 0.96282045, 0.11719643],
       [0.96474927, 0.48359832, 0.82002025, 0.90170698, 0.2808117 ],
       [0.23330435, 0.7225797 , 0.70509206, 0.168703  , 0.81205092]])

## 10) 生成随机索引， 元素不重复

In [25]:
np.random.permutation(10)

array([8, 9, 3, 4, 2, 6, 0, 1, 5, 7])

 ## 汇总
- <font color=red>np.ones(shape=(3,3))</font>  
- np.zeros(shape=(5,3),dtype=float,order='C')  
- np.full(shape=(3,3),fill_value=6)  
- np.eye(N,M=None,K=0,dtype=float)
- np.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None)
- np.arange(start,stop,step, dtype-None)
- **np.random.ranint(low,high=None,size=None,dtype='l')**
- np.random.randn(d0,d1,……dn) =>标准正太分布 [-1,0,1]  
- np.random.normal()  =>普通正态分布  
- np.random.random(size=(3,5))
- **np.random.permutation(10)** 

In [13]:
arr= np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])