# numpy的索引与切片


In [1]:
import numpy as np

In [2]:
# 一维数组，两种方式
array1 = np.array([1,2,3,4,5,6])
array1[1]

2

In [3]:
#通过索引访问元素
array1[[1]]

array([2])

In [4]:
# 使用布尔列表作为索引访问，True对应的值会被返回
array1[array1>3]

array([4, 5, 6])

In [5]:
#二维数组的索引
array2=np.random.randint(0,100,size=(5,6))
array2

array([[ 7, 90, 94, 43,  2,  1],
       [52, 38, 58, 21, 73, 72],
       [47, 73, 80, 21, 54, 23],
       [ 7, 20, 43, 87, 40, 38],
       [68, 39, 15,  3, 24, 33]])

In [6]:
#获取第一行第二个数据:方法一
array2[0][1]

90

In [7]:
#方法二：
array2[0,1]

90

In [8]:
#获取前两行,左开右闭
array2[0:2]

array([[ 7, 90, 94, 43,  2,  1],
       [52, 38, 58, 21, 73, 72]])

In [9]:
#获取前两列，行不做筛选，全部截取后， 再截取列
array2[:,0:2]

array([[ 7, 90],
       [52, 38],
       [47, 73],
       [ 7, 20],
       [68, 39]])

In [10]:
array3 = np.random.randint(10,100,size=(3,4,5))
array3

array([[[62, 82, 85, 24, 38],
        [91, 46, 68, 21, 23],
        [59, 45, 60, 40, 94],
        [28, 48, 35, 16, 75]],

       [[75, 15, 84, 29, 18],
        [88, 44, 56, 92, 75],
        [90, 98, 78, 15, 59],
        [27, 67, 96, 95, 21]],

       [[75, 48, 96, 94, 59],
        [77, 83, 93, 43, 96],
        [90, 55, 81, 15, 36],
        [55, 65, 52, 11, 57]]])

In [11]:
# 获取第一块，第一行
array3[0][0]

array([62, 82, 85, 24, 38])

In [12]:
# 获取第二块，第二行，第二个元素
array3[1,1,1]

44

In [13]:
#获取第三块，前两列, 中间行，全部取出后，在截取
array3[2,:,0:2]

array([[75, 48],
       [77, 83],
       [90, 55],
       [55, 65]])

In [14]:
array3[0:1]

array([[[62, 82, 85, 24, 38],
        [91, 46, 68, 21, 23],
        [59, 45, 60, 40, 94],
        [28, 48, 35, 16, 75]]])

# 对于切片，无论多少维，每一个维度范围都使用冒号表示，使用逗号分隔维度，